services:
  nginx:
    profiles:
      - disabled
  strapi:
    build:
      args:
        - WEBSITE_MAIN_URL=http://localhost:8080/
    environment:
      - WEBSITE_MAIN_URL=http://localhost:8080/
    command: npm run develop
  website:
    command: >
      sh -c "/opt/website/bootstrap.sh --dev"
    ports:
      - 8080:80
