services:
  nginx:
    restart: unless-stopped
    image: nginxinc/nginx-unprivileged
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/old_website:/old_website
      - ./storage/strapi_public:/strapi_public
      - ./website/public:/website_public
      - nextjs-static-volume:/nextjs_static
      - ./storage/nginx_cache:/var/cache/nginx
    depends_on:
      - strapi
      - website
      - meilisearch
  strapi:
    restart: unless-stopped
    build:
      args:
        - WEBSITE_MAIN_URL=${WEBSITE_MAIN_URL}
      context: ./strapi
    environment:
      - WEBSITE_MAIN_URL=${WEBSITE_MAIN_URL}
    env_file:
      - ./masterkey.env.private
      - ./strapi.env.private
    command: npm run start
    expose:
      - 80
    volumes:
      - type: bind
        source: ./storage/strapi_mod.db
        target: /strapi_mod.db
      - type: bind
        source: ./storage/strapi_public
        target: /strapi_public
    healthcheck:
      test: ["CMD-SHELL", "curl http://strapi/ | grep -i 'The server is running successfully'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5m
    ulimits:
      nofile:
        soft: 10000
        hard: 15000
    depends_on:
      - meilisearch
  website:
    restart: unless-stopped
    build:
      context: ./website
    environment:
      - PORT=80
      - STRAPI_URL_INTERNAL=http://strapi
      - MEILI_URL_INTERNAL=http://meilisearch
      - NEXT_PUBLIC_STRAPI_URL=${WEBSITE_MAIN_URL}/strapi
      - NEXT_PUBLIC_MEILISEARCH_URL=${WEBSITE_MAIN_URL}/meilisearch
    env_file:
      - ./masterkey.env.private
      - ./website.env.private
    command: >
      sh -c "/opt/website/bootstrap.sh"
    healthcheck:
      test: ["CMD-SHELL", "curl http://website/api/healthz | grep -i 'All good'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5m
    expose:
      - 80
    volumes:
      - nextjs-static-volume:/nextjs_static
      - ./storage/nginx_cache:/nginx_cache
    depends_on:
      strapi:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
  meilisearch:
    restart: unless-stopped
    container_name: meilisearch
    image: getmeili/meilisearch:v1.10
    environment:
      - MEILI_HTTP_ADDR=0.0.0.0:80
    env_file:
      - ./masterkey.env.private
    expose:
      - 80
    volumes:
      - ./storage/data.ms:/data.ms
    healthcheck:
      test: ["CMD-SHELL", "curl http://meilisearch/health | grep -i 'available'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5m
volumes:
  nextjs-static-volume:
